<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB; // For database transactions
use App\Constants\Status; // If you use it for remarks or other status-like fields in transaction details

class UserCoinBalance extends Model
{
    use HasFactory;

    protected $table = 'user_coin_balances';

    protected $fillable = [
        'user_id',
        'coin_type_id',
        'balance',
        'last_transaction_at',
    ];

    protected $casts = [
        'balance' => 'decimal:8', // Match precision with migration, e.g., 8 decimal places
        'last_transaction_at' => 'datetime',
    ];

    // Relationships
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function coinType()
    {
        return $this->belongsTo(CoinType::class);
    }

    /**
     * Atomically credit (increase) the user's balance for a specific coin type.
     * Creates a corresponding coin transaction record.
     *
     * @param float $amount Amount to credit (must be positive).
     * @param string $remark A remark for the transaction (e.g., 'api_credit', 'admin_adjustment').
     * @param array $transactionParams Additional parameters for the CoinTransaction record.
     *                                  Includes 'trx' (required unique ID), and optional: 'charge', 'details',
     *                                  'related_transaction_id', 'related_transaction_type',
     *                                  'game_api_key_id', 'created_by_admin_id'.
     * @return CoinTransaction The created coin transaction record.
     * @throws \InvalidArgumentException if amount is not positive or trx is missing.
     * @throws \Throwable on database error.
     */
    public function credit(float $amount, string $remark, array $transactionParams = []): CoinTransaction
    {
        if ($amount <= 0) {
            throw new \InvalidArgumentException('Credit amount must be positive.');
        }
        if (empty($transactionParams['trx'])) {
            // trx should ideally be generated by the calling service to ensure it's available
            // and potentially linked before this operation. If not provided, generate it.
            $transactionParams['trx'] = getTrx();
            // throw new \InvalidArgumentException('Unique transaction ID (trx) is required for coin transaction.');
        }


        return DB::transaction(function () use ($amount, $remark, $transactionParams) {
            // Lock the balance record for update to prevent race conditions
            // Ensure $this is the correct, up-to-date instance. It's safer to re-fetch if unsure.
            $lockedBalance = self::find($this->id); // Re-fetch to be certain, or ensure $this is fresh
            if(!$lockedBalance){ // Should not happen if $this is a valid model instance
                throw new \RuntimeException('UserCoinBalance record not found for locking.');
            }
            $lockedBalance = $lockedBalance->lockForUpdate()->first();


            $oldBalance = (float) $lockedBalance->balance;
            $newBalance = $oldBalance + $amount;

            $lockedBalance->balance = $newBalance;
            $lockedBalance->last_transaction_at = now();
            $lockedBalance->save();

            // Create CoinTransaction record
            $coinTransaction = CoinTransaction::create([
                'user_id' => $this->user_id,
                'coin_type_id' => $this->coin_type_id,
                'amount' => $amount, // Positive for credit
                'post_balance' => $newBalance,
                'charge' => (float) ($transactionParams['charge'] ?? 0),
                'trx_type' => '+',
                'remark' => $remark,
                'details' => $transactionParams['details'] ?? "Credited {$amount} {$this->coinType->code}",
                'trx' => $transactionParams['trx'],
                'related_transaction_id' => $transactionParams['related_transaction_id'] ?? null,
                'related_transaction_type' => $transactionParams['related_transaction_type'] ?? null,
                'game_api_key_id' => $transactionParams['game_api_key_id'] ?? null,
                'created_by_admin_id' => $transactionParams['created_by_admin_id'] ?? (auth('admin')->check() ? auth('admin')->id() : null),
            ]);

            return $coinTransaction;
        });
    }

    /**
     * Atomically debit (decrease) the user's balance for a specific coin type.
     * Creates a corresponding coin transaction record.
     *
     * @param float $amount Amount to debit (must be positive).
     * @param string $remark A remark for the transaction (e.g., 'item_purchase', 'api_debit').
     * @param array $transactionParams Additional parameters for the CoinTransaction record.
     * @return CoinTransaction The created coin transaction record.
     * @throws \InvalidArgumentException if amount is not positive or trx is missing.
     * @throws \App\Exceptions\InsufficientBalanceException if balance is not enough (custom exception preferred).
     * @throws \Throwable on database error.
     */
    public function debit(float $amount, string $remark, array $transactionParams = []): CoinTransaction
    {
        if ($amount <= 0) {
            throw new \InvalidArgumentException('Debit amount must be positive.');
        }
        if (empty($transactionParams['trx'])) {
            $transactionParams['trx'] = getTrx();
            // throw new \InvalidArgumentException('Unique transaction ID (trx) is required for coin transaction.');
        }

        return DB::transaction(function () use ($amount, $remark, $transactionParams) {
            $lockedBalance = self::find($this->id);
            if(!$lockedBalance){
                throw new \RuntimeException('UserCoinBalance record not found for locking.');
            }
            $lockedBalance = $lockedBalance->lockForUpdate()->first();

            $oldBalance = (float) $lockedBalance->balance;
            if ($oldBalance < $amount) {
                // Consider creating a custom exception for insufficient balance for better error handling
                // e.g., throw new \App\Exceptions\InsufficientBalanceException('Insufficient balance...');
                throw new \RuntimeException('Insufficient balance for ' . ($this->coinType->code ?? 'coin') . '. Required: ' . $amount . ', Available: ' . $oldBalance);
            }
            $newBalance = $oldBalance - $amount;

            $lockedBalance->balance = $newBalance;
            $lockedBalance->last_transaction_at = now();
            $lockedBalance->save();

            $coinTransaction = CoinTransaction::create([
                'user_id' => $this->user_id,
                'coin_type_id' => $this->coin_type_id,
                'amount' => -$amount, // Store debit as negative amount for consistency in sums, or positive with trx_type '-'
                'post_balance' => $newBalance,
                'charge' => (float) ($transactionParams['charge'] ?? 0),
                'trx_type' => '-',
                'remark' => $remark,
                'details' => $transactionParams['details'] ?? "Debited {$amount} {$this->coinType->code}",
                'trx' => $transactionParams['trx'],
                'related_transaction_id' => $transactionParams['related_transaction_id'] ?? null,
                'related_transaction_type' => $transactionParams['related_transaction_type'] ?? null,
                'game_api_key_id' => $transactionParams['game_api_key_id'] ?? null,
                'created_by_admin_id' => $transactionParams['created_by_admin_id'] ?? (auth('admin')->check() ? auth('admin')->id() : null),
            ]);

            return $coinTransaction;
        });
    }

    /**
     * Helper to get or create a balance record for a user and coin type.
     * Ensures that a balance record exists before attempting to credit/debit.
     *
     * @param int $userId
     * @param int $coinTypeId
     * @return self
     */
    public static function getOrCreateBalance(int $userId, int $coinTypeId): self
    {
        // Use firstOrCreate to prevent race conditions if two requests try to create it simultaneously.
        // The unique constraint on (user_id, coin_type_id) also helps.
        return self::firstOrCreate(
            ['user_id' => $userId, 'coin_type_id' => $coinTypeId],
            ['balance' => 0.00, 'last_transaction_at' => null] // last_transaction_at will be updated on first transaction
        );
    }
}
