name: Laravel CI/CD

on:
  push:
    branches: [ "main", "try3" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
    - name: Install Dependencies
      run: |
        cd core
        composer install --prefer-dist --no-progress --no-suggest
    - name: Prepare Laravel Application
      run: |
        cd core
        cp .env.example .env
        php artisan key:generate
    - name: Run Tests
      run: |
        cd core
        php artisan test
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/try3'
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /path/to/your/project
          git pull origin main
          cd core
          composer install --optimize-autoloader --no-dev
          php artisan optimize:clear
          php artisan migrate --force
